name             'openstack-wrapper'
maintainer       'Mostafa Zare'
maintainer_email 'mostafazare@gmail.com'
license          'MIT'
description      'Installs/Configures openstack-wrapper'
version          '0.1.0'

depends 'openstack-common', '>= 20.0.0'
depends 'openstack-ops-database', '>= 20.0.0'
depends 'openstack-ops-messaging', '>= 20.0.0'
depends 'openstack-identity', '>= 20.0.0'
depends 'openstack-image', '>= 20.0.0'
depends 'openstack-network', '>= 20.0.0'
depends 'openstack-compute', '>= 20.0.0'
depends 'openstack-block-storage', '>= 20.0.0'
depends 'openstack-bare-metal', '>= 20.0.0'
depends 'openstack-orchestration', '>= 20.0.0'
depends 'openstack-dns', '>= 20.0.0'
depends 'openstack-dashboard', '>= 20.0.0'
